---
- name: set version
  shell: "uuidgen -r | cut -c1-8"
  register: package_uuid
  delegate_to: localhost
  run_once: true

- name: removing packages
  block:
    - set_fact:
        package_update_type: "Remove Packages"
        package_update_run: "remove"
        package_update_cmd: "remove -y {{ packages_remove }}"
  when: packages_remove|length > 0

- name: removing job
  block:
    - name: getting yum id
      shell: "grep '{{ packages_remove_job }}' {{ package_uuid_file }} | cut -d '-' -f2"
      register: package_remove_yumid

    - set_fact:
        package_update_type: "Remove Packages"
        package_update_run: "remove_job"
        package_update_cmd: "history undo -y {{ package_remove_yumid.stdout }}"

  when: packages_remove_job|length > 0

- name: removing package
  shell: "sudo yum {{ package_update_cmd }}"
  register: package_remove_chk
  ignore_errors: true
#  - debug: var=package_remove_chk

- debug: msg={{ package_remove_chk.rc }}
  register: package_run
  when: (package_remove_chk.rc == 0) and (not "No Packages" in package_remove_chk.stdout) and (package_remove_chk is success)

- set_fact:
    package_update_date: "{{ package_remove_chk.start | regex_replace('.{16}$') }}"
    package_update_time: "{{ package_remove_chk.start | regex_replace('^.{0,11}') | regex_replace('.{10}$') }}"
    msg_job_time: "{{ lookup('pipe', 'date +%s') }}"
    msg_job_uuid: "{{ package_uuid.stdout }}"
  when: not package_run is skipped

- name: getting remove id
#  shell: "sudo yum history --setopt=history_list_view=commands | tail -n21 | grep {{ package_update_date }} | grep {{ package_update_time }} | head -n1 | awk '{print $1}'"
  shell: "sudo yum history info | grep 'Transaction ID' | cut -d ':' -f2 | awk '{print $1}'"
  register: package_id
  when: not package_run is skipped

- name: saving version
  shell: "echo {{ package_uuid.stdout }}-{{ package_id.stdout }} >> {{ package_uuid_file }}"
  when: not package_run is skipped
  become: no

- name: package cleanup
  shell: "sudo yum clean all"
  when: not package_run is skipped

#- set_fact:
#    packages_function_report: false

- set_fact:
    packages_function_report: false
    packages_function_alert: true
  when: not package_run is skipped

- set_fact:
    packages_function_report: false
    packages_function_alert: false
  when: package_run is skipped

